//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_mesage
    {
        public int Group_chat_ID { get; set; }
        public string Group_Name { get; set; }
        public string message { get; set; }
        public string from_user { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual GROUPS GROUPS { get; set; }
    }
}
