//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjektEntities : DbContext
    {
        public ProjektEntities()
            : base("name=ProjektEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BETS> BETS { get; set; }
        public virtual DbSet<DRIVERS> DRIVERS { get; set; }
        public virtual DbSet<FRIENDS> FRIENDS { get; set; }
        public virtual DbSet<GROUPS> GROUPS { get; set; }
        public virtual DbSet<INVITATIONS> INVITATIONS { get; set; }
        public virtual DbSet<MEMBERSHIPS> MEMBERSHIPS { get; set; }
        public virtual DbSet<MESSAGES> MESSAGES { get; set; }
        public virtual DbSet<PARTICIPANTS> PARTICIPANTS { get; set; }
        public virtual DbSet<RACES> RACES { get; set; }
        public virtual DbSet<SEASONS> SEASONS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TEAMS> TEAMS { get; set; }
        public virtual DbSet<USER> USER { get; set; }
    }
}
