//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPANTS
    {
        public int Participants_ID { get; set; }
        public int Season_ID { get; set; }
        public int Driver_ID { get; set; }
        public int Team_ID { get; set; }
    
        public virtual DRIVERS DRIVERS { get; set; }
        public virtual SEASONS SEASONS { get; set; }
        public virtual TEAMS TEAMS { get; set; }
    }
}
